# Generated by Django 3.2.11 on 2026-02-24 21：40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_status_jobseekerprofile_show_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='Project highlights or portfolio work'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_projects',
            field=models.BooleanField(default=True),
        ),
    ]