# Generated by Django 5.0 on 2026-02-25 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobseekerprofile_projects_show_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short summary about yourself'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Certifications, licenses, awards'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='desired_job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='desired_salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='featured_label',
            field=models.CharField(blank=True, help_text="Label shown above the embed, e.g. 'My Portfolio', 'Intro Video'", max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='featured_url',
            field=models.URLField(blank=True, help_text='Link to a website, portfolio, or project (displayed as a clickable card)'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='featured_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link for an introduction / project video'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='Spoken languages, e.g. English (Native), Spanish (Conversational)'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='open_to_relocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='open_to_remote',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_bio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_certifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_languages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='visa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='links',
            field=models.TextField(blank=True, help_text='GitHub, LinkedIn, portfolio URLs (one per line)'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='projects',
            field=models.TextField(blank=True, help_text='Key projects, coursework, open-source contributions'),
        ),
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate or offensive content'), ('spam', 'Spam or misleading links'), ('impersonation', 'Impersonation'), ('harmful', 'Harmful or dangerous content'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Optional additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.jobseekerprofile')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
