# Generated by Django 5.0 on 2026-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobseekerprofile_bio_jobseekerprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='commute_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum commute distance', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='distance_unit',
            field=models.CharField(choices=[('mi', 'Miles'), ('km', 'Kilometers')], default='mi', max_length=2),
        ),
    ]
