# Generated by Django 5.0 on 2026-03-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_savedcandidatesearch_candidatematchnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF or Word resume', null=True, upload_to='resumes/'),
        ),
    ]
