# Generated by Django 5.0 on 2026-03-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobseekerprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='show_resume',
            field=models.BooleanField(default=True),
        ),
    ]
