# Generated by Django 5.0 on 2026-03-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobseekerprofile_show_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='background_opacity',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='goal_applications',
            field=models.PositiveIntegerField(default=10, help_text='Target number of applications to submit'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='goal_filled',
            field=models.PositiveIntegerField(default=3, help_text='Target job postings filled'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='goal_offers',
            field=models.PositiveIntegerField(default=1, help_text='Target number of offers to receive'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='goal_offers_sent',
            field=models.PositiveIntegerField(default=5, help_text='Target offers to send'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='goal_reviews',
            field=models.PositiveIntegerField(default=20, help_text='Target applications to review'),
        ),
    ]
