# Generated by Django 5.0 on 2026-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobseekerprofile_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='background_opacity',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='goal_filled',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='goal_offers_sent',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='goal_reviews',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
